---
# For use with pre-commit.
# See usage instructions at http://pre-commit.com

- id: codetypo
  name: codetypo
  description: This hook runs CodeTypo spellchecker
  entry: codetypo-cli
  language: node
  types: [text]
  args:
    - --no-must-find-files
    - --no-progress
    - --no-summary
    - --gitignore
    - --files # this needs to be the last argument so that the paths are passed correctly.
